// MAT.9.1.1 (1/2): Gerçek sayıların üslü gösterimi ve üslü gösterimlerle işlemler.
// Sıra, giriş durumları, keşif tabloları ve problemler MEB 9. sınıf matematik ders kitabının 1. temasını izler (s. 13-24).
// Soruların hangi kaynaktaki hangi soru tipine göre yazıldığı her sorunun `kay` alanında durur.
import type { Konu } from './tip';

const KITAP = 'MEB 9. Sınıf Matematik Ders Kitabı (1. Kitap)';

const k: Konu = {
  id: 'mat-uslu', ad: 'Üslü Gösterim', dk: 17, tdk: 13,
  giris: 'Çok büyük ve çok küçük sayıları kısa yazmanın yolu. Kuralları ezberlemeyeceksin: her birini önce küçük bir tabloda kendin göreceksin, sonra gerçek bir problemde kullanacaksın.',
  day: {
    kod: 'MAT.9.1.1',
    kapsam: 'Bu ders öğrenme çıktısının üslü gösterim bölümünü işler: tanım, sıfır ve negatif üs, toplama, çıkarma, çarpma, bölme, üssün üssü ve bilimsel gösterim. Köklü gösterim bir sonraki derstedir.',
    surec: [
      'Gerçek sayıların üslü ve köklü gösterimleriyle yapılan işlemlere ilişkin varsayımlarda bulunur.',
      'Farklı örneklerden elde ettiği örüntüleri listeleyerek varsayımlarına yönelik genellemeler yapar.',
      'Varsayımları ile genellemelerini karşılaştırır.',
      'Elde ettiği genellemelerden üslü ve köklü gösterimlerle ilgili önermeler sunar.',
      'Üslü ve köklü gösterimlerle ilgili önermelerin kullanışlılığını problem durumlarında değerlendirir.',
      'Üslü ve köklü gösterimlerle ilgili matematiksel doğrulama yöntemlerini kullanır.',
      'Kullandığı matematiksel doğrulama yöntemlerini kullanışlılık açısından değerlendirir.',
    ],
    kitap: `${KITAP}, 1. Tema: Sayılar, sayfa 13-24`,
    sira: ['Gerçek Sayıların Üslü Gösterimi', 'Üslü Gösterimlerle Toplama ve Çıkarma', 'Tabanları Aynı Olan Üslü Gösterimlerle Çarpma ve Bölme', 'Üsleri Aynı Olan Üslü Gösterimlerle Çarpma ve Bölme', 'Üslü Gösterimin Üssünü Alma', 'Bilimsel Gösterim'],
  },
  yan: {
    carp: {
      ad: 'Üssü tabanla çarpmak',
      anlat: 'Üs, tabanın kaç kez kendisiyle çarpılacağını söyler; tabanla çarpılmaz.',
      ornek: '2^3 = 2·2·2 = 8 olur; 2·3 = 6 değil.',
    },
    parantez: {
      ad: 'Eksi işaretini üsse yanlış katmak',
      anlat: 'Parantez varsa eksi de tabana aittir: çift kuvvette sonuç pozitif, tek kuvvette negatif olur. Parantez yoksa önce üs alınır, eksi sonra başa konur.',
      ornek: '(−2)^4 = 16 ama −2^4 = −16. (−2)^3 = −8.',
    },
    negatif: {
      ad: 'Negatif üssün işareti değiştirdiğini sanmak',
      anlat: 'Negatif üs sayının işaretine dokunmaz; yalnızca çarpmaya göre tersini aldırır. Pozitif sayı pozitif, negatif sayı negatif kalır.',
      ornek: '2^{−3} = {1//8} olur; −8 değil. (−{1//3})^{−1} = −3 olur; 3 değil.',
    },
    sifir: {
      ad: 'Sıfırıncı kuvveti yanlış almak',
      anlat: 'Sıfırdan farklı her sayının sıfırıncı kuvveti 1\'dir. Üs birer birer azalırken sonuç her seferinde tabana bölünür: 2^1 = 2 sayısından bir adım sonra 2 ÷ 2 = 1 gelir.',
      ornek: '4^0 = 1 olur; 0 ya da 4 değil.',
    },
    toplam: {
      ad: 'Toplama ve çıkarmada üslerle işlem yapmak',
      anlat: 'Üsleri toplama ve çıkarma kuralları çarpma ile bölmeye aittir. Toplama ve çıkarmada üslere dokunulmaz; aynı üslü gösterimden kaç tane olduğu sayılır.',
      ornek: '5·10^9 − 0,2·10^9 = 4,8·10^9 olur; üs 9 olarak kalır. 2^3 + 2^3 = 2·2^3 olur; 2^6 değil.',
    },
    esitle: {
      ad: 'Üsleri eşitlemeden katsayıları toplamak',
      anlat: 'Katsayılar ancak taban da üs de aynıyken toplanıp çıkarılabilir. Üsler farklıysa önce hepsi aynı üsle yazılır.',
      ornek: '7,5·10^8 − 5,8·10^7 işleminde önce 5,8·10^7 = 0,58·10^8 yazılır; sonuç 6,92·10^8 olur, 1,7·10^8 değil.',
    },
    ortak: {
      ad: 'Ortak çarpan parantezinde kalan çarpanı unutmak',
      anlat: 'Bir terimi ortak çarpana böldüğünde geriye ne kaldığını tek tek yazman gerekir. Üs büyüdükçe kalan çarpan da büyür.',
      ornek: '3·2^{10} sayısını 2^7 parantezine alırsan geriye 3 değil, 3·2^3 = 24 kalır.',
    },
    uscarp: {
      ad: 'Çarpmada üsleri çarpmak',
      anlat: 'Tabanlar aynıyken çarpmada üsler toplanır, çünkü çarpanlar yan yana eklenir. Üsler yalnızca üssün üssü alınırken çarpılır.',
      ornek: '2^3·2^4 = 2^{3+4} = 2^7 olur; 2^{12} değil.',
    },
    bolme: {
      ad: 'Bölmede üsleri yanlış çıkarmak',
      anlat: 'Bölmede paydaki üsten paydadaki üs çıkarılır. Paydadaki üs negatifse çıkarma toplamaya döner; çünkü eksi bir sayıyı çıkarmak onu eklemektir.',
      ornek: '2^{10} ÷ 2^{−2} = 2^{10−(−2)} = 2^{12} olur; 2^8 değil.',
    },
    ustopla: {
      ad: 'Üssün üssünde üsleri toplamak',
      anlat: 'Üssün üssü, aynı paketin tekrar tekrar çarpılmasıdır: paket sayısı ile paketteki çarpan sayısı çarpılır.',
      ornek: '(3^2)^3 = 3^2·3^2·3^2 = 3^6 olur; 3^5 değil.',
    },
    eslestir: {
      ad: 'Aynı üs kuralını yanlış kullanmak',
      anlat: 'x^a·y^a = (x·y)^a kuralında üs değişmez, yalnızca tabanlar çarpılır. Kural da yalnızca üsler aynıyken geçerlidir; üsler farklıysa önce eşit sayıda çarpan ayrılır.',
      ornek: '2^3·5^3 = 10^3 olur; 10^6 değil. 2^7·5^9 çarpımında yalnızca 7 çift eşleşir: 10^7·5^2.',
    },
    basamak: {
      ad: 'Üssü basamak sayısı sanmak',
      anlat: '10^n sayısında 1\'in sağında n tane sıfır vardır; sayı n + 1 basamaklıdır. Önündeki katsayının basamakları da ayrıca sayılır.',
      ornek: '3·10^9 = 3 000 000 000 on basamaklıdır; dokuz değil.',
    },
    bilim: {
      ad: 'Virgülü kaydırırken üssü ayarlamamak',
      anlat: 'Bilimsel gösterimde katsayı 1 ile 10 arasında olmalıdır. Virgülü her bir basamak kaydırdığında üs de 1 değişir: virgül sola giderse üs artar, sağa giderse azalır.',
      ornek: '0,4·10^2 = 4·10^1 = 40 olur; 4 ya da 400 değil.',
    },
    kiyas: {
      ad: 'Yalnızca katsayıya ya da yalnızca üsse bakarak karşılaştırmak',
      anlat: 'Üsleri farklı yazılmış sayılar katsayılarına bakılarak karşılaştırılamaz. Önce hepsi aynı üsle yazılır, sonra katsayılar karşılaştırılır.',
      ornek: '9,8·10^3 sayısı 2,45·10^4 sayısından küçüktür; çünkü 9,8·10^3 = 0,98·10^4.',
    },
    dagit: {
      ad: 'Üssü toplamaya dağıtmak',
      anlat: 'Üs, çarpmaya dağılır ama toplamaya dağılmaz. Küçük sayılarla denemek bunu hemen gösterir.',
      ornek: '(1 + 2)^2 = 9 ama 1^2 + 2^2 = 5.',
    },
  },
  kartlar: [
    {
      id: 'tanim', baslik: 'Üslü gösterim ne söyler?',
      giris: 'İnsan beyninde yaklaşık 86 000 000 000 nöron vardır. Bir nötronun kütlesi ise yaklaşık 0,000 000 000 000 000 000 000 001 675 gramdır. Bu sayıları her seferinde böyle yazmak hem yorucu hem hataya açık.',
      metin: [
        'Aynı sayının art arda çarpımını kısa yazmanın yolu üslü gösterimdir. a^n yazımında **a** tabandır, **n** üstür: üs, tabanın kaç kez çarpılacağını söyler. 2^5 demek 2·2·2·2·2 demektir; 2·5 demek değildir.',
        '10\'un kuvvetleri özellikle işe yarar: 10^3 = 1000 ve 10^6 = 1 000 000. Üs, 1\'in sağındaki sıfır sayısıdır. Beyindeki nöron sayısı bu yüzden 8,6·10^{10} diye yazılır.',
        'Eksi işaretine dikkat et. Parantez varsa eksi de tabana aittir; parantez yoksa üs yalnızca sayıya aittir ve eksi en sona kalır. Tablonun son iki satırını karşılaştır.',
      ],
      tablo: {
        ad: 'Üslü gösterim ve yapılan işlem',
        bas: ['Üslü gösterim', 'Yapılan işlem', 'Sonuç'],
        sat: [
          ['1^4', '1·1·1·1', '1'],
          ['({2//3})^4', '{2//3}·{2//3}·{2//3}·{2//3}', '{16//81}'],
          ['(−2)^5', '(−2)·(−2)·(−2)·(−2)·(−2)', '−32'],
          ['(−3)^4', '(−3)·(−3)·(−3)·(−3)', '81'],
          ['−3^4', '−(3·3·3·3)', '−81'],
        ],
      },
      kural: ['a^n = a·a·…·a   (n tane a;  a taban, n üs)', '(−a)^n: n çiftse pozitif, n tekse negatif', '−a^n = −(a^n)'],
      ornek: { s: '(−2)^4 − 2^4 + (−1)^7 işleminin sonucu kaçtır?', a: ['(−2)^4 = 16   (parantez var, çift kuvvet: pozitif)', '2^4 = 16', '(−1)^7 = −1   (tek kuvvet: negatif)', '16 − 16 + (−1) = −1'] },
      baska: 'Bir kâğıdı ikiye katla: 2 kat. Bir daha katla: 4 kat. Bir daha: 8 kat. Her katlamada kat sayısı 2 ile çarpılır; 3 katlamadan sonra 2·2·2 = 2^3 = 8 kat olur. Üs, kaç kez katladığını sayar; sonucu bulmak için tabanı o kadar kez çarparsın.',
      soru: { s: '(−2)^3 kaçtır?', o: ['−8', '−6', '8'], d: 0, y: [null, 'carp', 'parantez'], neden: '(−2)·(−2)·(−2) = −8. Üs tek olduğu için sonuç negatif.' },
    },
    {
      id: 'ters', baslik: 'Sıfır ve negatif üs',
      giris: 'Bir hidrojen atomunun çekirdeğinin çapı yaklaşık 0,00000000000000175 metredir. Bu kadar küçük sayıları da üsle yazabilmek için üssün sıfır ve negatif olduğu durumları anlamak gerekir.',
      metin: [
        'Tabloya bak: 2\'nin kuvvetlerinde üs bir azaldığında sonuç 2\'ye bölünüyor. Aynı örüntüyü sürdürürsen üs 0 olduğunda 1\'e, üs negatif olduğunda kesirlere ulaşırsın.',
        'Demek ki negatif üs sayıyı negatif yapmaz; sayının **çarpmaya göre tersini** aldırır. a^{−n}, 1\'in a^n sayısına bölümüdür. Kesirlerde bu, pay ile paydanın yer değiştirmesi demektir.',
        'Sıfırdan farklı her sayının sıfırıncı kuvveti 1\'dir. Sıfırın pozitif kuvvetleri ise 0\'dır: 0^5 = 0.',
      ],
      tablo: {
        ad: 'Üs birer birer azalırken',
        bas: ['Üslü gösterim', '2^3', '2^2', '2^1', '2^0', '2^{−1}', '2^{−2}'],
        sat: [['Sonuç', '8', '4', '2', '1', '{1//2}', '{1//4}'], ['Öncekine göre', '', '÷ 2', '÷ 2', '÷ 2', '÷ 2', '÷ 2']],
      },
      kural: ['a^0 = 1   (a ≠ 0)', 'a^{−n} = {1//a^n}   (a ≠ 0)', '({a//b})^{−n} = ({b//a})^n'],
      ornek: { s: '4^{−1} + ({1//3})^{−2} + (−6)^0 işleminin sonucu kaçtır?', a: ['4^{−1} = {1//4}', '({1//3})^{−2} = 3^2 = 9   (kesir ters çevrilir, üs pozitif olur)', '(−6)^0 = 1   (sıfırdan farklı her sayının sıfırıncı kuvveti 1)', '{1//4} + 9 + 1 = {41//4}'] },
      baska: 'Üssü bir merdiven gibi düşün. Bir basamak yukarı çıkmak tabanla çarpmak, bir basamak aşağı inmek tabana bölmektir. 2^1 = 2 basamağından bir aşağı inersen 2 ÷ 2 = 1 olur: bu 2^0. Bir daha inersen 1 ÷ 2 = {1//2} olur: bu 2^{−1}. Hiçbir basamakta sayı negatife dönmez; yalnızca küçülür.',
      soru: { s: '5^{−2} kaçtır?', o: ['−25', '{1//25}', '−10'], d: 1, y: ['negatif', null, 'carp'], neden: '5^{−2} = {1//5^2} = {1//25}. Negatif üs sayıyı negatif yapmaz, tersini aldırır.' },
    },
    {
      id: 'topla', baslik: 'Toplama ve çıkarma',
      giris: 'Bir laboratuvarda incelenen 1 litre kanda 5·10^9 alyuvar, 6·10^6 akyuvar ve 0,2·10^9 trombosit sayılmıştır. Alyuvarlarla trombositlerin toplamı kaçtır?',
      metin: [
        'Tabloya bak: 3·5^{10} + 5^{10} demek, 5^{10} sayısından önce 3 tane, sonra 1 tane daha almak demektir. Toplam 4 tane 5^{10} eder. Üslü gösterim burada bir elma gibi sayılır: 3 elma ile 1 elma, 4 elma.',
        'Bunun adı **ortak çarpan parantezine almak**tır. Yalnızca tabanı da üssü de aynı olan üslü gösterimler bu şekilde toplanıp çıkarılabilir. Üslere dokunulmaz; toplanan ya da çıkarılan katsayılardır.',
        'Kandaki alyuvar ve trombosit toplamı böylece hemen bulunur: 5·10^9 + 0,2·10^9 = 5,2·10^9. Üsler farklı olsaydı önce eşitlemek gerekirdi; aşağıdaki örnek bunu gösteriyor.',
      ],
      tablo: {
        ad: 'Ortak çarpan parantezi',
        bas: ['İşlem', 'Ortak çarpan parantezi', 'Sonuç'],
        sat: [
          ['3·5^{10} + 5^{10}', '(3 + 1)·5^{10}', '4·5^{10}'],
          ['5·7^{12} − 2·7^{12}', '(5 − 2)·7^{12}', '3·7^{12}'],
          ['−7·11^5 + 4·11^5', '(−7 + 4)·11^5', '−3·11^5'],
          ['0,4·5^7 + 2,1·5^7', '(0,4 + 2,1)·5^7', '2,5·5^7'],
        ],
      },
      kural: ['a·x^n + b·x^n − c·x^n = (a + b − c)·x^n'],
      ornek: { s: 'Aynı doğrultudayken Merkür\'ün Güneş\'e uzaklığı yaklaşık 5,8·10^7 km, Jüpiter\'in Güneş\'e uzaklığı yaklaşık 7,5·10^8 km\'dir. Merkür, Güneş ile Jüpiter\'in arasındadır. Merkür ile Jüpiter arasındaki uzaklık yaklaşık kaç km\'dir?', a: ['İstenen uzaklık bir farktır: 7,5·10^8 − 5,8·10^7', 'Üsler farklı, önce eşitle: 5,8·10^7 = 0,58·10^8', 'Ortak çarpan parantezi: (7,5 − 0,58)·10^8', 'Sonuç: 6,92·10^8 km'] },
      baska: '10^8 yerine "yüz milyon" de. 7,5 yüz milyondan 0,58 yüz milyon çıkarırsan 6,92 yüz milyon kalır. "Yüz milyon" sözü işlem boyunca hiç değişmedi; üslü gösterim de aynı şekilde olduğu gibi kalır. Ama birimler farklıysa, biri yüz milyon öteki on milyonsa, önce aynı birime çevirmen gerekir.',
      soru: { s: '2^3 + 2^3 işleminin sonucu hangisidir?', o: ['2^6', '2^4', '4^3'], d: 1, y: ['toplam', null, 'toplam'], neden: '2^3 + 2^3 = 8 + 8 = 16 = 2^4. Ortak çarpanla: (1 + 1)·2^3 = 2·2^3. Üsler toplanmadı; iki tane 2^3 sayıldı.' },
    },
    {
      id: 'carp', baslik: 'Çarpma ve bölme: tabanlar aynıysa',
      giris: 'Ankara\'daki barajlarda 2001 yılının ocak ayında yaklaşık 4·10^6 metreküp, 2024 yılının ocak ayında yaklaşık 1,6·10^8 metreküp su ölçülmüştür. 1 metreküp 1000 litredir. 2001\'deki su kaç litredir?',
      metin: [
        'Tablodaki çarpımları açık yaz ve çarpanları say: 2^3·2^4 çarpımında önce 3 tane, sonra 4 tane 2 var; toplam 7 tane. Çarpmada çarpanlar yan yana eklenir, bu yüzden **üsler toplanır**.',
        'Bölmede paydaki ve paydadaki çarpanlar birbirini götürür: 2^5 ÷ 2^3 işleminde 5 çarpandan 3\'ü sadeleşir, 2 tanesi kalır. Bu yüzden **üsler çıkarılır**. Paydadaki üs daha büyükse sonuç negatif üslü çıkar: 6^3 ÷ 6^5 = 6^{−2}.',
        'Barajdaki su: 4·10^6 metreküp, 4·10^6·10^3 = 4·10^9 litre eder.',
      ],
      tablo: {
        ad: 'Çarpanları say',
        bas: ['İşlem', 'Açık hâli', 'Sonuç'],
        sat: [
          ['2^3·2^4', '(2·2·2)·(2·2·2·2)', '2^7'],
          ['(−6)^2·(−6)^3', '(−6)·(−6)·(−6)·(−6)·(−6)', '(−6)^5'],
          ['2^5 ÷ 2^3', '{2·2·2·2·2//2·2·2}', '2^2'],
          ['11^6 ÷ 11^2', '6 çarpandan 2\'si sadeleşir', '11^4'],
        ],
      },
      kural: ['x^a·x^b = x^{a+b}', '{x^a//x^b} = x^{a−b}   (x ≠ 0)'],
      ornek: { s: 'Yeryüzündeki kumsallarda yaklaşık 4·10^{21} kum tanesi olduğu düşünülüyor. Arşimet\'in evreni doldurmak için hesapladığı kum tanesi sayısı bunun 2·10^{42} katıdır. Arşimet\'in bulduğu sayı kaçtır?', a: ['"Katı" çarpma demektir: (4·10^{21})·(2·10^{42})', 'Katsayılar kendi arasında, 10\'un kuvvetleri kendi arasında çarpılır: (4·2)·(10^{21}·10^{42})', 'Tabanlar aynı, üsler toplanır: 10^{21+42} = 10^{63}', 'Sonuç: 8·10^{63}. Bu, 8\'in sağına 63 sıfır yazılan 64 basamaklı sayıdır.'] },
      baska: 'Üsleri çarpan sayacı gibi düşün. 10^{21} içinde 21 tane 10 var, 10^{42} içinde 42 tane. İkisini çarparsan elinde 21 + 42 = 63 tane 10 olur. Bölerken tersine, paydadaki her 10 paydan bir 10 götürür: 10^8 ÷ 10^6 işleminde 8 − 6 = 2 tane 10 kalır.',
      soru: { s: '3^5·3^2 ÷ 3^4 işleminin sonucu hangisidir?', o: ['3^3', '3^{10}', '3^{11}'], d: 0, y: [null, 'uscarp', 'bolme'], neden: '3^{5+2−4} = 3^3. Çarparken üsler toplanır, bölerken çıkarılır.' },
    },
    {
      id: 'ayniUs', baslik: 'Çarpma ve bölme: üsler aynıysa',
      giris: 'A = 3·2^{11} ve B = 7·5^{11} sayılarının çarpımı kaç basamaklıdır? Çarpımı hesaplamaya kalkarsan çok uğraşırsın; oysa 2 ile 5\'in çarpımının 10 etmesi işi birkaç satıra indirir.',
      metin: [
        'Tabloda tabanlar farklı ama üsler aynı. 2^3·5^3 çarpımını açıp çarpanları ikişer ikişer eşleştir: her 2 bir 5 ile yan yana gelir ve üç tane (2·5) oluşur. Üs aynı kalır, **tabanlar çarpılır**.',
        'Bölmede de aynı eşleştirme yapılır: 6^4 ÷ 5^4, dört tane {6//5} kesrinin çarpımıdır.',
        'Bu kural en çok 2 ile 5 yan yana geldiğinde işe yarar; çünkü 2·5 = 10 eder ve 10\'un kuvveti sayının sonundaki sıfırları verir.',
      ],
      tablo: {
        ad: 'Çarpanları eşleştir',
        bas: ['İşlem', 'Açık hâli', 'Sonuç'],
        sat: [
          ['2^3·5^3', '(2·5)·(2·5)·(2·5)', '10^3'],
          ['3^4·4^4', '(3·4)·(3·4)·(3·4)·(3·4)', '12^4'],
          ['(−2)^5·(−7)^5', '5 tane (−2)·(−7) çarpımı', '14^5'],
          ['6^4 ÷ 5^4', '{6//5}·{6//5}·{6//5}·{6//5}', '({6//5})^4'],
        ],
      },
      kural: ['x^a·y^a = (x·y)^a', '{x^a//y^a} = ({x//y})^a   (y ≠ 0)'],
      ornek: { s: 'A = 3·2^{11} ve B = 7·5^{11} olduğuna göre A·B kaç basamaklıdır?', a: ['A·B = (3·7)·(2^{11}·5^{11})', 'Üsler aynı, tabanlar çarpılır: 2^{11}·5^{11} = (2·5)^{11} = 10^{11}', 'A·B = 21·10^{11}: 21 yazılır, sağına 11 tane sıfır konur', 'Basamak sayısı: 2 + 11 = 13'] },
      baska: 'Bir halk oyununda 3 kız ile 3 erkek eşleşsin. Her kız bir erkekle çift olur ve 3 çift oluşur. 2^3·5^3 çarpımında da 3 tane 2 ile 3 tane 5 vardır; her 2 bir 5 ile çift olur ve 3 tane 10 oluşur. Sayılar eşit değilse, örneğin 3 tane 2 ile 5 tane 5 varsa, yalnızca 3 çift kurulur ve 2 tane 5 açıkta kalır.',
      soru: { s: '4^5·25^5 çarpımı hangisine eşittir?', o: ['100^5', '100^{10}', '29^5'], d: 0, y: [null, 'eslestir', null], neden: 'Üsler aynı: tabanlar çarpılır, üs olduğu gibi kalır. (4·25)^5 = 100^5.' },
    },
    {
      id: 'ussu', baslik: 'Üssün üssü',
      giris: 'Veri depolama birimleri arasında şu ilişki vardır: 1 GB = 2^{10} MB ve 1 GB = (2^{10})^3 bayt. 1 GB kaç bayttır? Cevabı 2\'nin tek bir kuvveti olarak yazmak için üssün üssünü almayı bilmek gerekir.',
      metin: [
        'Tabloya bak: (3^2)^3 demek, 3^2 sayısını 3 kez yan yana yazıp çarpmak demektir. Tabanlar aynı olduğu için üsler toplanır: 2 + 2 + 2. Aynı sayıyı 3 kez toplamak onu 3 ile çarpmaktır; bu yüzden **üsler çarpılır**.',
        '1 GB = (2^{10})^3 = 2^{30} bayt, yani 1 073 741 824 bayt eder.',
        'Bu kural tabanı değiştirmek için de kullanılır: 4 = 2^2 olduğundan 4^5 = (2^2)^5 = 2^{10}; 27 = 3^3 olduğundan 27^2 = 3^6. Farklı görünen tabanları aynı tabana çevirmek birçok sorunun anahtarıdır.',
      ],
      tablo: {
        ad: 'Paketleri say',
        bas: ['İşlem', 'Açık hâli', 'Sonuç'],
        sat: [
          ['(3^2)^3', '3^2·3^2·3^2 = 3^{2+2+2}', '3^6'],
          ['(5^4)^2', '5^4·5^4 = 5^{4+4}', '5^8'],
          ['(2^{10})^3', '2^{10}·2^{10}·2^{10} = 2^{10+10+10}', '2^{30}'],
          ['(2^3)^{−2}', '{1//(2^3)^2} = {1//2^6}', '2^{−6}'],
        ],
      },
      kural: ['(x^a)^b = x^{a·b}'],
      ornek: { s: 'A = 3·(2^3)^6·5^{14} sayısı kaç basamaklıdır? Değerini hesaplamadan bul.', a: ['Üssün üssü: (2^3)^6 = 2^{18}, yani A = 3·2^{18}·5^{14}', '5\'in üssü 14; 2\'lerden 14 tanesini ayır: 2^{18} = 2^4·2^{14}', 'Üsleri aynı olanları eşleştir: 2^{14}·5^{14} = 10^{14}', 'A = 3·2^4·10^{14} = 48·10^{14}', '48\'in sağında 14 sıfır var: 2 + 14 = 16 basamak'] },
      baska: 'Parantezin içini bir paket gibi düşün. (3^2)^3 yazımında paketten 3 tane var ve her pakette 2 tane 3 çarpanı duruyor. Toplam çarpan sayısı 3 paket × 2 çarpan = 6. Üssün üssünde üslerin çarpılmasının nedeni budur: paket sayısı ile paketteki çarpan sayısı çarpılır.',
      soru: { s: '8^4 hangisine eşittir?', o: ['2^7', '2^{12}', '2^{32}'], d: 1, y: ['ustopla', null, null], neden: '8 = 2^3 olduğundan 8^4 = (2^3)^4 = 2^{12}. Üssün üssünde üsler çarpılır.' },
    },
    {
      id: 'bilimsel', baslik: 'Bilimsel gösterim',
      giris: 'Adana, Kahramanmaraş ve Tokat\'ın Çanakkale\'ye kara yolu uzaklıkları sırasıyla yaklaşık 1,09·10^6 m, 123·10^4 m ve 10,54·10^5 m olarak verilmiş. Hangisi en uzak? Üsler de katsayılar da farklı yazıldığı için ilk bakışta söylemek zor.',
      metin: [
        'Karışıklığı önlemek için ortak bir biçim kullanılır: sayı, **1 ile 10 arasında bir katsayı** ile 10\'un bir kuvvetinin çarpımı olarak yazılır. Buna bilimsel gösterim denir. Katsayı 1 olabilir ama 10 olamaz.',
        'Bir sayıyı bu biçime getirirken virgülü kaydırırsın. Virgül bir basamak sola kayarsa katsayı 10 kat küçülür; sayının değeri değişmesin diye üs 1 artar. Virgül sağa kayarsa üs azalır.',
        'Üç uzaklığı da 10^6 ile yazınca karşılaştırma katsayılara kalır: 1,054 < 1,09 < 1,23. En yakın Tokat, en uzak Kahramanmaraş\'tır. Üsler farklı olsaydı önce üsse bakılırdı: pozitif sayılarda üssü büyük olan büyüktür.',
      ],
      tablo: {
        ad: 'Virgül kayarken üs değişir',
        bas: ['Sayı', 'Virgül', 'Bilimsel gösterim'],
        sat: [
          ['123·10^4', '2 basamak sola, üs 2 artar', '1,23·10^6'],
          ['10,54·10^5', '1 basamak sola, üs 1 artar', '1,054·10^6'],
          ['0,2·10^9', '1 basamak sağa, üs 1 azalır', '2·10^8'],
          ['0,00000000000000175', '15 basamak sağa', '1,75·10^{−15}'],
        ],
      },
      kural: ['a·10^n   (1 ≤ a < 10, n tam sayı)', 'Karşılaştırırken önce üsler eşitlenir, sonra katsayılara bakılır.'],
      ornek: { s: 'İnsan vücudundaki atom sayısı, kütle (kg) ile 10^{26} çarpılarak yaklaşık olarak bulunur. 6,02·10^{23} tane atom 1 mol sayılır. Kütlesi 66,22 kg olan bir kişinin vücudunda yaklaşık kaç mol atom vardır?', a: ['Atom sayısı: 66,22·10^{26} = 6,622·10^{27}', 'Mol sayısı bir bölmedir: {6,622·10^{27}//6,02·10^{23}}', 'Katsayılar bölünür: 6,622 ÷ 6,02 = 1,1. Üsler çıkarılır: 10^{27−23} = 10^4', 'Sonuç: 1,1·10^4 mol'] },
      baska: 'Bilimsel gösterimi bir adres gibi düşün. 10\'un kuvveti sayının hangi mahallede olduğunu söyler: binler mi, milyonlar mı, milyarlar mı? Katsayı ise o mahalledeki kapı numarasıdır. İki sayıyı karşılaştırırken önce mahalleye bakarsın; mahalle aynıysa kapı numarasına.',
      soru: { s: 'Aşağıdakilerden hangisi bilimsel gösterimdir?', o: ['12,5·10^6', '0,8·10^{−3}', '3,7·10^{−5}'], d: 2, y: ['bilim', 'bilim', null], neden: 'Katsayı 1 ile 10 arasında olmalı: 3,7 uygun. 12,5 fazla büyük, 0,8 fazla küçük.' },
    },
    {
      id: 'onerme', baslik: 'Bir kural her zaman doğru mu?',
      giris: 'Selin şöyle düşünüyor: "Çarpmada üsler toplanıyorsa toplamada da toplanır: 2^3 + 2^2 = 2^5." Kontrol edelim: 2^3 + 2^2 = 8 + 4 = 12, oysa 2^5 = 32. Tek bir örnek, Selin\'in tahminini çürütmeye yetti.',
      metin: [
        'Matematikte bir tahmine **varsayım** denir. Birkaç örnekte denenip örüntü görülünce **genelleme** yapılır; genelleme açıkça yazılınca **önerme** olur. Bu derste her kuralı böyle bulduk: önce tablo, sonra kural.',
        'Bir önermenin yanlış olduğunu göstermek için ona uymayan **tek bir örnek** yeter; buna karşıt örnek denir. Doğru olduğunu göstermek için ise örnek yetmez: önermenin her sayı için geçerli olduğu gösterilmelidir. Bunun yolu, işlemi harflerle açık yazıp çarpanları saymaktır.',
        'x^a·x^b = x^{a+b} önermesinin doğrulaması: x^a içinde a tane, x^b içinde b tane x çarpanı vardır. Çarpımda toplam a + b tane x olur. Sayılar ne olursa olsun bu sayım değişmez; önerme doğrudur.',
      ],
      tablo: {
        ad: 'Önce bir örnekle dene',
        bas: ['Önerme', 'Deneme', 'Sonuç'],
        sat: [
          ['x^a + x^b = x^{a+b}', '2^3 + 2^2 = 12  ama  2^5 = 32', 'Yanlış'],
          ['(x + y)^a = x^a + y^a', '(1 + 2)^2 = 9  ama  1^2 + 2^2 = 5', 'Yanlış'],
          ['(x·y)^a = x^a·y^a', '(2·3)^2 = 36  ve  2^2·3^2 = 36', 'Tutuyor, doğrulanmalı'],
          ['(x^a)^b = x^{a·b}', '(2^3)^2 = 64  ve  2^6 = 64', 'Tutuyor, doğrulanmalı'],
        ],
      },
      kural: ['Yanlışlamak için tek bir karşıt örnek yeter.', 'Doğrulamak için her sayıda geçerli bir gerekçe gerekir.'],
      ornek: { s: '"Bir sayının negatif kuvveti her zaman negatiftir." önermesi doğru mudur?', a: ['Bir örnek dene: 2^{−1} = {1//2}', '{1//2} pozitif bir sayıdır; önermeye uymuyor', 'Tek bir karşıt örnek yeterlidir: önerme yanlıştır', 'Doğrusu: negatif üs sayının çarpmaya göre tersini aldırır, işaretini değiştirmez'] },
      baska: '"Bütün kuşlar uçar" cümlesini çürütmek için tek bir penguen göstermek yeter. Ama "bütün kuşların kanadı vardır" cümlesini kanıtlamak için birkaç kuş göstermek yetmez; kuş olmanın tanımına bakman gerekir. Matematikte de böyledir: karşıt örnek çürütür, tanıma dayanan gerekçe doğrular.',
      soru: { s: '"(x + y)^2 = x^2 + y^2" önermesini çürüten karşıt örnek hangisidir?', o: ['x = 0 ve y = 5', 'x = 1 ve y = 2', 'x = 3 ve y = 0'], d: 1, neden: 'x = 1 ve y = 2 için sol taraf 3^2 = 9, sağ taraf 1 + 4 = 5 eder; eşit değil. Öteki iki örnekte iki taraf eşit çıkar, yani onlar önermeyi çürütmez.' },
    },
  ],
  ozet: [
    'a^n, n tane a\'nın çarpımıdır. Parantez yoksa eksi tabana ait değildir: (−2)^4 = 16 ama −2^4 = −16.',
    'a^0 = 1 ve a^{−n} = {1//a^n}. Negatif üs sayıyı negatif yapmaz, tersini aldırır.',
    'Toplama ve çıkarma yalnızca taban ve üs aynıyken yapılır; katsayılar toplanır: a·x^n + b·x^n = (a + b)·x^n.',
    'Tabanlar aynıysa çarpmada üsler toplanır, bölmede çıkarılır.',
    'Üsler aynıysa tabanlar çarpılır ya da bölünür. Özellikle 2^n·5^n = 10^n.',
    'Üssün üssünde üsler çarpılır: (x^a)^b = x^{a·b}.',
    'Bilimsel gösterim a·10^n biçimindedir ve 1 ≤ a < 10 olmalıdır. Karşılaştırmadan önce üsleri eşitle.',
    'Bir önermeyi tek karşıt örnek çürütür; doğrulamak için çarpanları sayan genel bir gerekçe gerekir.',
  ],
  sorular: [
    {
      id: 's1', z: 1, kart: 'tanim', tur: 'islem',
      s: '−3^2 + (−3)^2 + (−2)^3 işleminin sonucu kaçtır?',
      o: ['10', '−26', '−8', '8', '−18'], d: 2, y: ['parantez', 'parantez', null, 'parantez', 'carp'],
      c: ['−3^2: parantez yok, üs yalnızca 3\'e aittir: −(3^2) = −9', '(−3)^2 = (−3)·(−3) = 9', '(−2)^3 = (−2)·(−2)·(−2) = −8', '−9 + 9 + (−8) = −8'],
      h: '-(3**2) + (-3)**2 + (-2)**3 === -8',
      kay: `${KITAP}, 1. Uygulama tablosundaki gösterim türleri`,
    },
    {
      id: 's2', z: 1, kart: 'ters', tur: 'islem',
      s: '2^{−2} + (−{1//3})^{−1} + 4^0 − (−2)^3 işleminin sonucu kaçtır?',
      o: ['{25//4}', '{21//4}', '{49//4}', '−{39//4}', '2'], d: 0, y: [null, 'sifir', 'negatif', 'parantez', 'negatif'],
      c: ['2^{−2} = {1//2^2} = {1//4}', '(−{1//3})^{−1}: kesir ters çevrilir, işaret aynı kalır: −3', '4^0 = 1', '(−2)^3 = −8; önündeki eksiyle birlikte −(−8) = +8', '{1//4} − 3 + 1 + 8 = {25//4}'],
      h: 'Math.abs(2**-2 + (-1/3)**-1 + 4**0 - (-2)**3 - 25/4) < 1e-9',
      kay: `${KITAP}, 1. Sıra Sizde`,
    },
    {
      id: 's3', z: 1, kart: 'topla', tur: 'baglam',
      b: ['Bir laboratuvarda incelenen 1 litre kanda 5·10^9 alyuvar, 6·10^6 akyuvar ve 0,2·10^9 trombosit sayılmıştır.'],
      s: 'Buna göre bu kanda alyuvar sayısı trombosit sayısından kaç fazladır?',
      o: ['4,994·10^9', '4,8', '4,8·10^{18}', '5,2·10^9', '4,8·10^9'], d: 4, y: [null, 'toplam', 'toplam', null, null],
      c: ['"Kaç fazla" bir farktır: 5·10^9 − 0,2·10^9', 'Taban ve üs aynı; ortak çarpan parantezi: (5 − 0,2)·10^9', 'Sonuç: 4,8·10^9. Üs değişmedi, yalnızca katsayılar çıkarıldı.'],
      h: '5e9 - 0.2e9 === 4.8e9',
      kay: `${KITAP}, toplama ve çıkarma bölümünün giriş durumu (kan hücreleri)`,
    },
    {
      id: 's4', z: 2, kart: 'carp', tur: 'baglam',
      b: ['Ankara\'daki barajlarda 2001 yılının ocak ayında yaklaşık 4·10^6 metreküp, 2024 yılının ocak ayında yaklaşık 1,6·10^8 metreküp su ölçülmüştür.'],
      s: 'Buna göre 2024\'teki su miktarı 2001\'dekinin kaç katıdır?',
      o: ['4', '40', '400', '4·10^{13}', '2,5·10^{−2}'], d: 1, y: ['bilim', null, 'bilim', 'bolme', null],
      c: ['"Kaç katı" bir bölmedir: {1,6·10^8//4·10^6}', 'Katsayılar bölünür: 1,6 ÷ 4 = 0,4', 'Tabanlar aynı, üsler çıkarılır: 10^{8−6} = 10^2', '0,4·10^2 = 40. Su miktarı 40 katına çıkmıştır.'],
      h: '1.6e8 / 4e6 === 40',
      kay: `${KITAP}, çarpma ve bölme bölümünün giriş durumu (Ankara barajları)`,
    },
    {
      id: 's5', z: 2, kart: 'ayniUs', tur: 'islem',
      s: 'A = 12·2^7·5^9 sayısı kaç basamaklıdır?',
      o: ['9', '10', '11', '17', '18'], d: 1, y: ['basamak', null, 'eslestir', 'eslestir', 'eslestir'],
      c: ['5\'lerden 7 tanesini ayır: 5^9 = 5^7·5^2', 'Üsleri aynı olanları eşleştir: 2^7·5^7 = (2·5)^7 = 10^7', 'A = 12·5^2·10^7 = 12·25·10^7 = 300·10^7', '300\'ün sağında 7 sıfır var: 3 + 7 = 10 basamak'],
      h: 'String(12 * 2**7 * 5**9).length === 10',
      kay: `${KITAP}, 4. Uygulama 5. madde ve 3. Örnek (basamak sayısı) tipinde`,
    },
    {
      id: 's6', z: 3, kart: 'ussu', tur: 'islem',
      s: '3^x = 2 olduğuna göre 9^{2x+1} ifadesinin değeri kaçtır?',
      o: ['108', '25', '144', '48', '36'], d: 2, y: ['ustopla', 'toplam', null, null, null],
      c: ['Tabanı 3\'e çevir: 9 = 3^2, yani 9^{2x+1} = (3^2)^{2x+1}', 'Üssün üssünde üsler çarpılır: 3^{4x+2}', 'Üsteki toplamı çarpıma ayır: 3^{4x+2} = 3^{4x}·3^2 = (3^x)^4·9', '3^x = 2 yerine yaz: 2^4·9 = 16·9 = 144'],
      h: 'Math.abs(9**(2*Math.log(2)/Math.log(3)+1) - 144) < 1e-6',
      kay: `${KITAP}, 2. Sıra Sizde 2. sorudan uyarlandı`,
    },
    {
      id: 's7', z: 2, kart: 'bilimsel', tur: 'baglam',
      b: ['Bir radyo istasyonu, bulunduğu noktadan en çok 2,45·10^4 metre uzağa yayın ulaştırabilmektedir. Üç dinleyicinin istasyona uzaklıkları tabloda verilmiştir.'],
      t: { bas: ['Dinleyici', 'İstasyona uzaklık (m)'], sat: [['Defne', '9,8·10^3'], ['Emre', '2,6·10^4'], ['Kerem', '0,23·10^5']] },
      s: 'Buna göre yayın bu dinleyicilerden hangilerine ulaşır?',
      o: ['Yalnız Defne', 'Yalnız Kerem', 'Defne ve Emre', 'Defne ve Kerem', 'Defne, Emre ve Kerem'], d: 3, y: ['kiyas', 'kiyas', 'kiyas', null, null],
      c: ['Hepsini sınırla aynı üsle yaz: sınır 2,45·10^4 m', 'Defne: 9,8·10^3 = 0,98·10^4. 0,98 < 2,45 olduğundan yayın ulaşır', 'Emre: 2,6·10^4. 2,6 > 2,45 olduğundan yayın ulaşmaz', 'Kerem: 0,23·10^5 = 2,3·10^4. 2,3 < 2,45 olduğundan yayın ulaşır', 'Yayın Defne ve Kerem\'e ulaşır'],
      h: '9.8e3 <= 2.45e4 && 2.6e4 > 2.45e4 && 0.23e5 <= 2.45e4',
      kay: `${KITAP}, 1. Tema Ölçme ve Değerlendirme 10. sorudan uyarlandı (sayılar ve adlar değiştirildi)`,
    },
    {
      id: 's8', z: 3, kart: 'topla', tur: 'baglam',
      b: ['Ece, evdeki elektrik tüketimini incelediği bir proje hazırlıyor. Üç cihazın gücünü ve bir günde çalıştığı süreyi tabloya yazıyor. Bir cihazın tükettiği enerji (watt saat), gücü ile çalışma süresinin çarpımıdır.'],
      t: { bas: ['Cihaz', 'Güç (watt)', 'Günlük süre (saat)'], sat: [['LED ampul', '2^4', '8'], ['Televizyon', '2^6', '4'], ['Buzdolabı', '2^7', '24']] },
      s: 'Buna göre bu üç cihazın bir günde tükettiği toplam enerji kaç watt saattir?',
      o: ['27·2^7', '3·2^{25}', '6·2^7', '5·2^{10}', '2^{13} + 3·2^{21}'], d: 0, y: [null, 'toplam', 'ortak', 'esitle', 'uscarp'],
      c: ['Enerji = güç × süre. Süreleri de 2\'nin kuvvetiyle yaz: 8 = 2^3, 4 = 2^2 ve 24 = 3·2^3', 'LED ampul: 2^4·2^3 = 2^7.   Televizyon: 2^6·2^2 = 2^8.   Buzdolabı: 2^7·3·2^3 = 3·2^{10}', 'Toplam: 2^7 + 2^8 + 3·2^{10}. Üsler farklı; hepsini 2^7 cinsinden yaz: 2^8 = 2·2^7 ve 3·2^{10} = 24·2^7', 'Ortak çarpan parantezi: (1 + 2 + 24)·2^7 = 27·2^7', 'Kontrol: 128 + 256 + 3072 = 3456 ve 27·128 = 3456'],
      h: '2**4*8 + 2**6*4 + 2**7*24 === 27 * 2**7',
      kay: 'MEB Bağlam Temelli Çoktan Seçmeli Soru Yazım Kılavuzu (2026), ortaöğretim matematik örnek sorusunun biçiminde: cihaz tablosu, günlük kullanım, üslü gösterimle toplam',
    },
    {
      id: 's9', z: 2, kart: 'carp', tur: 'muhakeme',
      b: ['Bora, (2^3)^2·2^4 ÷ 2^{−2} ÷ 2^5 işlemini soldan sağa aşağıdaki adımlarla yapmıştır.'],
      t: { bas: ['Adım', 'Yapılan işlem'], sat: [['1', '(2^3)^2 = 2^6'], ['2', '2^6·2^4 = 2^{10}'], ['3', '2^{10} ÷ 2^{−2} = 2^8'], ['4', '2^8 ÷ 2^5 = 2^3'], ['5', '2^3 = 8']] },
      s: 'Buna göre Bora ilk hatayı hangi adımda yapmıştır?',
      o: ['1. adım', '2. adım', '3. adım', '4. adım', '5. adım'], d: 2, y: ['ustopla', 'uscarp', null, 'bolme', 'carp'],
      c: ['1. adım doğru: üssün üssünde üsler çarpılır, 3·2 = 6', '2. adım doğru: tabanlar aynı, üsler toplanır, 6 + 4 = 10', '3. adım hatalı: bölmede üsler çıkarılır ve 10 − (−2) = 12 olmalıydı. Bora eksi 2\'yi çıkarmak yerine 2 çıkarmış', 'Doğru sonuç: 2^{12} ÷ 2^5 = 2^7 = 128'],
      h: '(2**3)**2 * 2**4 / 2**-2 / 2**5 === 128',
      kay: `${KITAP}, 1. Tema Ölçme ve Değerlendirme 11. soru tipinde: "ilk hata hangi adımda"`,
    },
    {
      id: 's10', z: 3, kart: 'onerme', tur: 'muhakeme',
      s: 'x ve y sıfırdan farklı gerçek sayılar, a pozitif tam sayıdır. Aşağıdaki önermelerden hangisi her zaman doğrudur?',
      o: ['x^a + x^a = x^{2a}', '(x + y)^a = x^a + y^a', '(x^a)^a = x^{2a}', '(x·y)^a = x^a·y^a', 'x^a·y^a = (x·y)^{2a}'], d: 3, y: ['toplam', 'dagit', 'ustopla', null, 'eslestir'],
      c: ['Her seçeneği küçük sayılarla dene: x = 3, y = 2 ve a = 3', 'x^a + x^a = 27 + 27 = 54 ama x^{2a} = 3^6 = 729. Tutmadı', '(x + y)^a = 5^3 = 125 ama x^a + y^a = 27 + 8 = 35. Tutmadı', '(x^a)^a = 27^3 = 3^9 ama x^{2a} = 3^6. Tutmadı. x^a·y^a = 216 ama (x·y)^{2a} = 6^6. Tutmadı', '(x·y)^a = x^a·y^a her sayı için geçerlidir: a tane (x·y) çarpımında a tane x ve a tane y vardır'],
      h: '(3*2)**3 === 3**3 * 2**3 && 3**3 + 3**3 !== 3**6 && (3+2)**3 !== 3**3 + 2**3 && (3**3)**3 !== 3**6 && 3**3 * 2**3 !== (3*2)**6',
      kay: 'Öğretim programı MAT.9.1.1 süreç bileşenleri: önerme sunma ve doğrulama',
    },
  ],
  acik: [
    {
      id: 'a1', baslik: 'Işık yılı',
      b: ['Işığın hızı yaklaşık 3·10^5 km/sn, Güneş\'in Dünya\'ya uzaklığı yaklaşık 1,5·10^8 km\'dir. Bir yılda yaklaşık 3,15·10^7 saniye vardır.'],
      alt: ['Güneş\'ten çıkan ışık Dünya\'ya kaç saniyede ulaşır? Sonucu bilimsel gösterimle yazınız.', 'Işığın bir yılda aldığı yol, yani 1 ışık yılı kaç kilometredir? Sonucu bilimsel gösterimle yazınız.'],
      adim: [
        { p: 2, m: 'Süre = yol ÷ hız ilişkisini kurma: {1,5·10^8//3·10^5}' },
        { p: 2, m: 'Katsayıları bölme ve üsleri çıkarma: 0,5·10^3' },
        { p: 1, m: 'Bilimsel gösterime çevirme: 5·10^2 saniye' },
        { p: 2, m: 'Yol = hız × süre ilişkisini kurma: (3·10^5)·(3,15·10^7)' },
        { p: 2, m: 'Katsayıları çarpma ve üsleri toplama: 9,45·10^{12}' },
        { p: 1, m: 'Sonucu birimiyle yazma: 9,45·10^{12} km' },
      ],
      kay: `${KITAP}, bilimsel gösterim araştırma ödevindeki "1 ışık yılı" hesabı`,
    },
    {
      id: 'a2', baslik: 'Önermeyi doğrula',
      b: ['Elif, tabloyu inceleyip şu genellemeye ulaşıyor: "Tabanları aynı olan üslü gösterimler çarpılırken üsler toplanır."'],
      t: { bas: ['İşlem', 'Açık hâli', 'Sonuç'], sat: [['2^3·2^4', '(2·2·2)·(2·2·2·2)', '2^7'], ['5^2·5^3', '…', '…'], ['7^4·7', '…', '…']] },
      alt: ['Tablodaki boşlukları doldurunuz.', 'x sıfırdan farklı bir gerçek sayı, a ve b pozitif tam sayı olmak üzere x^a·x^b = x^{a+b} önermesini doğrulayınız.', '"x^a + x^b = x^{a+b}" önermesinin yanlış olduğunu bir karşıt örnekle gösteriniz.'],
      adim: [
        { p: 1, m: '5^2·5^3 = (5·5)·(5·5·5) = 5^5' },
        { p: 1, m: '7^4·7 = (7·7·7·7)·7 = 7^5' },
        { p: 2, m: 'x^a ve x^b çarpımlarını açık yazma: x^a içinde a tane, x^b içinde b tane x çarpanı' },
        { p: 2, m: 'Çarpımda toplam a + b tane x çarpanı olduğunu belirtme' },
        { p: 1, m: 'Sonucu yazma: x^a·x^b = x^{a+b}' },
        { p: 2, m: 'Uygun bir karşıt örnek verme: örneğin x = 2, a = 3 ve b = 2 için 2^3 + 2^2 = 12' },
        { p: 1, m: 'İki tarafın eşit olmadığını gösterme: 2^5 = 32 ve 32 ≠ 12' },
      ],
      kay: `${KITAP}, 3. Uygulama: varsayım, tablo, önerme ve doğrulama adımları`,
    },
    {
      id: 'a3', baslik: 'Kaç basamaklı?',
      alt: ['A = 5·(2^4)^3·5^{10} sayısının kaç basamaklı olduğunu, sayının değerini hesaplamadan bulunuz.', 'Kullandığınız yöntemi bir iki cümleyle açıklayınız.'],
      adim: [
        { p: 2, m: 'Üssün üssü: (2^4)^3 = 2^{12}' },
        { p: 2, m: '2\'lerden 10 tanesini ayırma: 2^{12} = 2^2·2^{10}' },
        { p: 2, m: 'Üsleri aynı olanları birleştirme: 2^{10}·5^{10} = 10^{10}' },
        { p: 2, m: 'A = 5·2^2·10^{10} = 20·10^{10} ve basamak sayısı: 2 + 10 = 12' },
        { p: 2, m: 'Açıklama: sayı 10\'un kuvveti cinsinden yazıldı; 10^{10} sondaki sıfırları, 20 baştaki basamakları verir' },
      ],
      kay: `${KITAP}, 3. Örnek`,
    },
  ],
};
export default k;
