// MAT.9.1.1 (2/2): Gerçek sayıların köklü gösterimi ve köklü gösterimlerle işlemler.
// Sıra, giriş durumları, keşif tabloları ve problemler MEB 9. sınıf matematik ders kitabının 1. temasını izler (s. 24-36).
// Soruların hangi kaynaktaki hangi soru tipine göre yazıldığı her sorunun `kay` alanında durur.
import type { Konu } from './tip';

const KITAP = 'MEB 9. Sınıf Matematik Ders Kitabı (1. Kitap)';

const k: Konu = {
  id: 'mat-koklu', ad: 'Köklü Gösterim', dk: 17, tdk: 13,
  giris: 'Alanı bilinen bir karenin kenarı ya da bir cismin düşme süresi çoğu zaman tam sayı çıkmaz. Bu sayıları yazmanın yolu köklü gösterimdir. Üslü gösterimde öğrendiğin her kural burada yeniden işine yarayacak.',
  day: {
    kod: 'MAT.9.1.1',
    kapsam: 'Bu ders öğrenme çıktısının köklü gösterim bölümünü işler: rasyonel üs ile kök arasındaki ilişki, köklü gösterimlerle toplama, çıkarma, çarpma, bölme, kökün kökü, kök derecelerini eşitleme, eşlenik ve yaklaşık değer.',
    surec: [
      'Gerçek sayıların üslü ve köklü gösterimleriyle yapılan işlemlere ilişkin varsayımlarda bulunur.',
      'Farklı örneklerden elde ettiği örüntüleri listeleyerek varsayımlarına yönelik genellemeler yapar.',
      'Varsayımları ile genellemelerini karşılaştırır.',
      'Elde ettiği genellemelerden üslü ve köklü gösterimlerle ilgili önermeler sunar.',
      'Üslü ve köklü gösterimlerle ilgili önermelerin kullanışlılığını problem durumlarında değerlendirir.',
      'Üslü ve köklü gösterimlerle ilgili matematiksel doğrulama yöntemlerini kullanır.',
      'Kullandığı matematiksel doğrulama yöntemlerini kullanışlılık açısından değerlendirir.',
    ],
    kitap: `${KITAP}, 1. Tema: Sayılar, sayfa 24-36`,
    sira: ['Gerçek Sayıların Köklü Gösterimi', 'Üslü ve Köklü Gösterimlerin Birbiri Cinsinden İfade Edilmesi', 'Köklü Gösterimlerle Toplama, Çıkarma, Çarpma, Bölme ve Kökün Kökü', 'Kök Dereceleri Farklı Olan Köklü Gösterimlerle Çarpma ve Bölme', 'Köklü Gösterimlerin Eşleniğini Bulma', 'Yaklaşık Değer'],
  },
  yan: {
    kokNeg: {
      ad: 'Kökte işaret kuralını karıştırmak',
      anlat: 'Karekök hiçbir zaman negatif çıkmaz: √(a^2), a sayısının mutlak değeridir. Derecesi tek olan kökte ise içerideki işaret korunur.',
      ornek: '√((−3)^2) = √9 = 3 olur; −3 değil. √[3](−8) = −2 olur; 2 değil.',
    },
    yari: {
      ad: 'Kökü ya da kesirli üssü bölme sanmak',
      anlat: 'Karekök almak ikiye bölmek değildir; "hangi sayının karesi bu?" sorusunun cevabıdır. Kesirli üs de tabanı o kesirle çarpmak değildir.',
      ornek: '√64 = 8 olur; 32 değil. 27^{{2//3}} = 9 olur; 18 değil.',
    },
    rasyonel: {
      ad: 'Rasyonel üste pay ile paydanın görevini karıştırmak',
      anlat: 'x^{{m//n}} yazımında payda kökün derecesidir, pay içerideki üstür. İkisi de uygulanmalıdır: önce kök alınır, sonra kuvvet.',
      ornek: '16^{{3//4}}: önce √[4]16 = 2, sonra 2^3 = 8.',
    },
    disari: {
      ad: 'Kök dışına çıkarırken karekök almayı unutmak',
      anlat: 'Kök içindeki tam kare çarpan dışarı kendisi olarak değil, karekökü olarak çıkar. Tersine, dışarıdaki sayı içeri karesi alınarak girer.',
      ornek: '√48 = √(16·3) = 4√3 olur; 16√3 değil.',
    },
    kokTopla: {
      ad: 'Kök içlerini toplamak ya da çıkarmak',
      anlat: 'Toplama ve çıkarmada kök içlerine dokunulmaz. Yalnızca kök içi ve derecesi aynı olan terimlerin katsayıları toplanır; bu yüzden önce kök dışına çıkarılır.',
      ornek: '√9 + √16 = 3 + 4 = 7 olur; √25 = 5 değil.',
    },
    kare: {
      ad: 'Köklü ifadenin karesini eksik almak',
      anlat: 'a√b sayısının karesi alınırken hem katsayının hem kökün karesi alınır: (a√b)^2 = a^2·b.',
      ornek: '(5√3)^2 = 25·3 = 75 olur; 15 ya da 25√3 değil.',
    },
    derece: {
      ad: 'Dereceleri eşitlemeden çarpmak',
      anlat: 'Dereceleri farklı kökler tek kök altına doğrudan giremez. Önce dereceler ortak bir kata getirilir; bunu yaparken içerideki üs de aynı sayıyla çarpılır.',
      ornek: '√2·√[3]2 = √[6](2^3)·√[6](2^2) = √[6]32 olur; √[6]4 ya da √[5]4 değil.',
    },
    siralama: {
      ad: 'Yalnızca kök içine ya da dereceye bakarak sıralamak',
      anlat: 'Dereceleri farklı kökler, kök içindeki sayılara bakılarak sıralanamaz. Önce dereceler eşitlenir, sonra kök içleri karşılaştırılır.',
      ornek: '√2 = √[6]8 ve √[6]6 karşılaştırılırsa √2 daha büyüktür; kök içi küçük olduğu hâlde.',
    },
    kokKok: {
      ad: 'Kökün kökünde dereceleri toplamak',
      anlat: 'Kökün kökü, üssün üssüdür; dereceler çarpılır.',
      ornek: '√(√[3]x) = √[6]x olur; √[5]x değil.',
    },
    eslenik: {
      ad: 'Eşleniği yanlış kurmak',
      anlat: 'Eşlenik, ortadaki işaretin değiştirilmiş hâlidir ve çarpım iki karenin farkını verir: (√a − √b)·(√a + √b) = a − b. Toplam değil, fark çıkar.',
      ornek: '(√7 − √3)·(√7 + √3) = 7 − 3 = 4 olur; 10 değil.',
    },
    paydaKok: {
      ad: 'Kesri genişletirken payı ya da paydayı unutmak',
      anlat: 'Bir kesrin değeri ancak pay ve payda aynı sayıyla çarpılırsa değişmez. Yalnızca birini çarparsan başka bir sayı elde edersin.',
      ornek: '{6//√3} = {6·√3//√3·√3} = {6√3//3} = 2√3.',
    },
    yuvarla: {
      ad: 'Parça sayısını yuvarlamamak ya da aşağı yuvarlamak',
      anlat: 'Top, panel ya da paket hâlinde satılan bir şeyden kesirli sayıda alınamaz. İhtiyaç 11,2 top çıkıyorsa 11 top yetmez; bir üst tam sayıya çıkılır.',
      ornek: '112 m için 10 metrelik toplardan 12 tane gerekir; 11 tane 110 m eder.',
    },
  },
  kartlar: [
    {
      id: 'kok', baslik: 'Karekök ve n. dereceden kök',
      gorsel: { tip: 'kare', alan: 21 },
      giris: 'Yüzey alanı 21 m² olan kare şeklindeki bir halının bir kenarı kaç metredir? Kendisiyle çarpılınca 21 eden sayı bir tam sayı değildir: 4·4 = 16 az gelir, 5·5 = 25 fazla.',
      metin: [
        'Bu sayıya **karekök 21** denir ve √21 diye yazılır. Karekök almak, kare almanın tersidir: √25 = 5, çünkü 5^2 = 25. √21 ise 4 ile 5 arasındadır.',
        'Aynı fikir daha büyük kuvvetler için de geçerlidir. Hacmi 8 birimküp olan küpün kenarı, küpü 8 eden sayıdır: √[3]8 = 2, çünkü 2^3 = 8. Kök işaretinin üstündeki küçük sayıya **kökün derecesi** denir; karekökte derece 2\'dir ve yazılmaz.',
        'İşarete dikkat et: karekök hiçbir zaman negatif çıkmaz. (−5)^2 = 25 olsa da √25 = 5\'tir. Derecesi çift olan kökün içi negatif olamaz; derecesi tek olan kökün içi negatif olabilir.',
      ],
      tablo: {
        ad: 'Kök, kuvvetin tersidir',
        bas: ['Köklü gösterim', 'Neden?', 'Sonuç'],
        sat: [['√49', '7^2 = 49', '7'], ['√[3]8', '2^3 = 8', '2'], ['√[4]16', '2^4 = 16', '2'], ['√[3](−27)', '(−3)^3 = −27', '−3'], ['√((−5)^2)', '√25', '5']],
      },
      kural: ['√[n](a^n) = a   (n tek ise)', '√[n](a^n) = |a|   (n çift ise)', 'Derecesi çift olan kökün içi negatif olamaz.'],
      ornek: { s: '√25 + √[4]16 − √0 + 2·√[3](−27) işleminin sonucu kaçtır?', a: ['√25 = 5, çünkü 5^2 = 25', '√[4]16 = 2, çünkü 2^4 = 16', '√0 = 0', '√[3](−27) = −3, çünkü (−3)^3 = −27', '5 + 2 − 0 + 2·(−3) = 1'] },
      baska: 'Karekökü bir soru gibi oku: "Hangi sayıyı kendisiyle çarparsam bunu bulurum?" √49 için cevap 7. Küp kök için soru şudur: "Hangi sayıyı üç kez çarparsam bunu bulurum?" √[3]8 için cevap 2. Kök, sayıyı ikiye ya da üçe bölmek değildir; çarpımı o sayıyı veren çarpanı aramaktır.',
      soru: { s: '√64 kaçtır?', o: ['32', '8', '−8'], d: 1, y: ['yari', null, 'kokNeg'], neden: '8·8 = 64 olduğundan √64 = 8. Karekök yarıya bölmek değildir ve negatif çıkmaz.' },
    },
    {
      id: 'rasyonel', baslik: 'Kök ile üs arasındaki köprü',
      gorsel: { tip: 'eslestir', ad: 'Aynı sayıyı bul', cift: [['25^{{1//2}}', '5'], ['8^{{1//3}}', '2'], ['√[3]27', '3'], ['√49', '7']] },
      giris: '9 sayısının yarım kuvveti olur mu? Üslü gösterimin kurallarına güvenirsek olur: 9^{{1//2}}·9^{{1//2}} = 9^1 = 9 etmelidir. Kendisiyle çarpılınca 9 veren sayı ise √9, yani 3\'tür.',
      metin: [
        'Demek ki yarım kuvvet karekök demektir: x^{{1//2}} = √x. Aynı düşünceyle x^{{1//3}} = √[3]x olur; çünkü üç tanesinin çarpımı x^1 eder.',
        'Genel olarak kesirli üste **payda kökün derecesi**, **pay içerideki üs** olur. Tabloyu soldan sağa da sağdan sola da okuyabilirsin: her köklü gösterim üslü, her rasyonel üslü gösterim köklü yazılabilir.',
        'Bu köprü çok işe yarar: kökle ilgili bütün kurallar, bildiğin üs kurallarından çıkar. Yeni bir şey ezberlemene gerek kalmaz.',
      ],
      tablo: {
        ad: 'Üslü gösterimden köklü gösterime',
        bas: ['Üslü gösterim', 'Kökün derecesi', 'İçerideki üs', 'Köklü gösterim'],
        sat: [
          ['2^{{3//2}}', '2', '3', '√(2^3) = √8'],
          ['3^{{1//2}}', '2', '1', '√3'],
          ['5^{{2//3}}', '3', '2', '√[3](5^2) = √[3]25'],
          ['7^{{3//5}}', '5', '3', '√[5](7^3)'],
          ['16^{{1//4}}', '4', '1', '√[4]16 = 2'],
        ],
      },
      kural: ['x^{{m//n}} = √[n](x^m)   (x > 0;  n kökün derecesi)', 'x^{{1//2}} = √x'],
      ornek: { s: '(16^{{1//4}} + 625^{{1//2}})^{{1//3}} işleminin sonucu kaçtır?', a: ['16^{{1//4}} = √[4]16 = 2, çünkü 2^4 = 16', '625^{{1//2}} = √625 = 25, çünkü 25^2 = 625', 'Parantezin içi: 2 + 25 = 27', '27^{{1//3}} = √[3]27 = 3, çünkü 3^3 = 27'] },
      baska: 'Üssü bir yolculuk gibi düşün: x^1, x sayısına tek adımda varmaktır. Bu yolu iki eşit çarpma adımında yürümek istersen her adım x^{{1//2}} olur ve iki adımın çarpımı x eder. Kendisiyle çarpılınca x veren sayı √x olduğuna göre yarım adım, kareköktür. Üç eşit adım istersen her adım küp köktür.',
      soru: { s: '8^{{2//3}} kaçtır?', o: ['4', '{16//3}', '√(8^3)'], d: 0, y: [null, 'yari', 'rasyonel'], neden: '8^{{2//3}} = √[3](8^2) = √[3]64 = 4. Payda kökün derecesi, pay içerideki üs.' },
    },
    {
      id: 'disari', baslik: 'Kök dışına çıkarmak',
      gorsel: { tip: 'kok-cikar', sayilar: [72, 48, 108, 1200] },
      giris: 'Ahmet Bey\'in kare şeklindeki arazisi 1200 m² büyüklüğündedir. Arazinin bir kenarı √1200 metredir. Bu sayıyı daha tanıdık bir biçimde yazabilir miyiz?',
      metin: [
        'Çarpımın karekökü, kareköklerin çarpımıdır. Nedeni üs kuralıdır: (x·y)^{{1//2}} = x^{{1//2}}·y^{{1//2}}. Öyleyse kök içindeki sayıyı, biri tam kare olan iki çarpana ayırabilirsen tam kare olan dışarı çıkar.',
        '1200 = 400·3 ve 400 = 20^2 olduğundan √1200 = √400·√3 = 20√3. Arazinin kenarı 20√3 metredir.',
        'Tersi de yapılabilir: dışarıdaki sayı karesi alınarak içeri girer. 3√2 = √(3^2·2) = √18. Bu, köklü sayıları karşılaştırırken işe yarar.',
      ],
      tablo: {
        ad: 'Tam kare çarpanı bul',
        bas: ['Sayı', 'Tam kare · kalan', 'Sonuç'],
        sat: [['√12', '√(4·3)', '2√3'], ['√48', '√(16·3)', '4√3'], ['√75', '√(25·3)', '5√3'], ['√108', '√(36·3)', '6√3'], ['√1200', '√(400·3)', '20√3']],
      },
      kural: ['√(a^2·b) = a√b   (a ≥ 0, b ≥ 0)', 'a√b = √(a^2·b)'],
      ornek: { s: '√72 sayısını a√b biçiminde yaz.', a: ['72\'yi tam kare bir çarpanla yaz: 72 = 36·2', '√72 = √36·√2', '√36 = 6 olduğundan √72 = 6√2', 'Kontrol: 6√2 = √(36·2) = √72'] },
      baska: 'Kök işaretini bir kapı gibi düşün: kapıdan yalnızca çiftler çıkabilir. 12 = 2·2·3 çarpanlarında bir çift 2 var; çift kapıdan tek bir 2 olarak çıkar, eşi olmayan 3 içeride kalır: √12 = 2√3. 72 = 2·2·2·3·3 çarpanlarında bir çift 2 ile bir çift 3 var; dışarı 2·3 = 6 çıkar, eşsiz kalan 2 içeride kalır: 6√2.',
      soru: { s: '√50 hangisine eşittir?', o: ['25√2', '5√2', '2√5'], d: 1, y: ['disari', null, 'disari'], neden: '50 = 25·2 ve √25 = 5 olduğundan √50 = 5√2. Dışarı 25 değil, 25\'in karekökü çıkar.' },
    },
    {
      id: 'topla', baslik: 'Toplama ve çıkarma',
      gorsel: {
        tip: 'grupla', ad: 'Hemen toplanır mı?', kutu: ['Hemen toplanır', 'Önce kök dışına çıkar'],
        oge: [['3√2 + 5√2', 0], ['√12 + √27', 1], ['7√5 − 2√5', 0], ['√8 + √2', 1], ['6√3 − √3', 0], ['√50 − √18', 1]],
      },
      giris: 'Bir deneyde iki cisim farklı yüksekliklerden bırakılmış; yere düşme süreleri √48 saniye ve √108 saniye olarak hesaplanmıştır. İki süre arasındaki fark kaç saniyedir?',
      metin: [
        'Köklü gösterimler de üslü gösterimler gibi toplanır: yalnızca **kökün derecesi ve kökün içi aynı** olanlar, ortak çarpan parantezine alınarak. 4√5 + 2√5 demek, √5 sayısından 4 + 2 = 6 tane almak demektir.',
        'Kök içleri farklı görünüyorsa önce kök dışına çıkar; çoğu zaman aynı köke iner. √108 = 6√3 ve √48 = 4√3 olduğundan fark 6√3 − 4√3 = 2√3 saniyedir.',
        'Kök içleri gerçekten farklıysa toplam daha fazla sadeleşmez: √2 + √3 öylece kalır. Kök içlerini toplamak yanlıştır: √9 + √16 = 3 + 4 = 7 eder, oysa √25 = 5\'tir.',
      ],
      tablo: {
        ad: 'Üslü gösterimde ne yapıyorsan aynısı',
        bas: ['Üslü gösterimle', 'Köklü gösterimle', 'Sonuç'],
        sat: [
          ['4·5^{{1//3}} + 2·5^{{1//3}}', '4√[3]5 + 2√[3]5', '6√[3]5'],
          ['4·6^{{1//5}} − 2·6^{{1//5}}', '4√[5]6 − 2√[5]6', '2√[5]6'],
          ['3^{{2//3}} + 8·3^{{2//3}} − 2·3^{{2//3}}', '√[3]9 + 8√[3]9 − 2√[3]9', '7√[3]9'],
        ],
      },
      kural: ['a·√[n]x + b·√[n]x − c·√[n]x = (a + b − c)·√[n]x'],
      ornek: { s: '√75 − 2√12 + 5√27 işleminin sonucu kaçtır?', a: ['Hepsini kök dışına çıkar: √75 = 5√3 ve √12 = 2√3 ve √27 = 3√3', 'Yerine yaz: 5√3 − 2·2√3 + 5·3√3', '5√3 − 4√3 + 15√3', 'Ortak çarpan parantezi: (5 − 4 + 15)√3 = 16√3'] },
      baska: '√3 yerine "elma" de. 5 elma − 4 elma + 15 elma = 16 elma. Ama 2 elma ile 3 armut toplanınca 5 elma da olmaz, 5 armut da: √2 ile √3 de böyle ayrı kalır. Önce kök dışına çıkarmak, meyvelerin aslında aynı olup olmadığını anlamanın yoludur: √12 ile √27 farklı görünür ama ikisi de √3 cinsindendir.',
      soru: { s: '√8 + √18 işleminin sonucu hangisidir?', o: ['√26', '5√2', '6√2'], d: 1, y: ['kokTopla', null, null], neden: '√8 = 2√2 ve √18 = 3√2 olduğundan toplam 5√2. Kök içleri toplanmaz.' },
    },
    {
      id: 'carp', baslik: 'Çarpma, bölme ve kökün kökü',
      giris: 'Bahar Hanım\'ın evinde mutfak, kiler ve salon kare şeklindedir. Mutfağın alanı 20 m², kilerin alanı 5 m²\'dir. Salonun bir kenarı, mutfak ile kilerin birer kenarının toplamı kadardır. Salonun alanı kaç metrekaredir?',
      metin: [
        'Dereceleri aynı olan kökler tek kök altında çarpılır ve bölünür. Nedeni yine üs kuralıdır: x^{{1//n}}·y^{{1//n}} = (x·y)^{{1//n}}.',
        'Bahar Hanım\'ın evi: mutfağın kenarı √20 = 2√5 m, kilerin kenarı √5 m. Salonun kenarı 2√5 + √5 = 3√5 m, alanı 3√5·3√5 = 9·5 = 45 m². Bir sayının karekökü kendisiyle çarpılınca kök kalkar: √5·√5 = 5.',
        'Kökün kökü alınırken dereceler çarpılır; çünkü bu, üssün üssüdür: (x^{{1//3}})^{{1//2}} = x^{{1//6}}.',
      ],
      tablo: {
        ad: 'Aynı dereceli kökler tek kök altında',
        bas: ['İşlem', 'Tek kök altında', 'Sonuç'],
        sat: [
          ['√2·√3', '√(2·3)', '√6'],
          ['√[3]10 ÷ √[3]5', '√[3]({10//5})', '√[3]2'],
          ['√[5]24·√[5]4 ÷ √[5]3', '√[5]({24·4//3})', '√[5]32 = 2'],
          ['√(√[3]15)', 'dereceler çarpılır: 2·3', '√[6]15'],
        ],
      },
      kural: ['√[n]x·√[n]y = √[n](x·y)', '{√[n]x//√[n]y} = √[n]({x//y})', '√[m](√[n]x) = √[m·n]x', '√x·√x = x'],
      ornek: { s: 'Bahar Hanım mutfak, kiler ve salonun zeminini metrekaresi 975 TL olan parke ile kaplatacaktır. Ödeyeceği tutar kaç TL\'dir?', a: ['Mutfağın kenarı √20 = 2√5 m, kilerin kenarı √5 m', 'Salonun kenarı: 2√5 + √5 = 3√5 m', 'Salonun alanı: 3√5·3√5 = 9·5 = 45 m²', 'Toplam alan: 20 + 5 + 45 = 70 m²', 'Tutar: 70·975 = 68 250 TL'] },
      baska: 'Aynı dereceli kökleri çarpmak, aynı boy kutuları birleştirmek gibidir: içindekiler tek kutuda toplanır, √2·√3 = √6. Kökün kökü ise kutunun içindeki kutudur: önce küp kökünü, sonra karekökünü alıyorsan sayıyı toplamda 3·2 = 6 eşit çarpana ayırıyorsun demektir; bu da 6. dereceden köktür.',
      soru: { s: '√12·√3 kaçtır?', o: ['6', '√15', '36'], d: 0, y: [null, 'kokTopla', null], neden: '√12·√3 = √36 = 6. Çarpmada kök içleri çarpılır, toplanmaz; sonra kök alınır.' },
    },
    {
      id: 'derece', baslik: 'Dereceleri farklı kökler',
      giris: '√2 ile √[3]3 çarpılabilir mi? Dereceleri farklı olduğu için tek kök altına hemen giremezler. Kesirlerde paydaları eşitlediğin gibi burada da kök derecelerini eşitlemen gerekir.',
      metin: [
        'Bir kökün derecesi ile içerideki üs aynı sayıyla çarpılırsa ya da bölünürse değeri değişmez; çünkü rasyonel üste pay ile payda aynı sayıyla genişletilmiş olur: 3^{{1//2}} = 3^{{3//6}}, yani √3 = √[6](3^3).',
        'İki kökü çarpmak için derecelerini ortak bir kata getir. √2 ile √[3]3 için ortak derece 6\'dır: √2 = √[6](2^3) = √[6]8 ve √[3]3 = √[6](3^2) = √[6]9. Çarpım √[6]72 olur.',
        'Aynı yol sıralamada da kullanılır: dereceler eşitlenince kök içi büyük olan sayı büyüktür.',
      ],
      tablo: {
        ad: 'Genişletme ve sadeleştirme',
        bas: ['Köklü gösterim', 'Üsse yapılan işlem', 'Elde edilen eşitlik'],
        sat: [
          ['√3', '{1//2} kesri 3 ile genişler: {3//6}', '√3 = √[6](3^3)'],
          ['√[3]2', '{1//3} kesri 2 ile genişler: {2//6}', '√[3]2 = √[6](2^2)'],
          ['√[4](5^6)', '{6//4} kesri 2 ile sadeleşir: {3//2}', '√[4](5^6) = √(5^3)'],
          ['√[12](3^{16})', '{16//12} kesri 4 ile sadeleşir: {4//3}', '√[12](3^{16}) = √[3](3^4)'],
        ],
      },
      kural: ['√[n](x^m) = √[n·k](x^{m·k})', 'Çarpmadan, bölmeden ve sıralamadan önce dereceler eşitlenir.'],
      ornek: { s: 'a = √[6]3, b = √[3]2 ve c = √[9]7 sayılarını küçükten büyüğe sırala.', a: ['Dereceler 6, 3 ve 9; hepsinin ortak katı 18', 'a = √[6]3 = √[18](3^3) = √[18]27', 'b = √[3]2 = √[18](2^6) = √[18]64', 'c = √[9]7 = √[18](7^2) = √[18]49', 'Kök içleri: 27 < 49 < 64, yani a < c < b'] },
      baska: 'Kesirleri toplamadan önce paydaları eşitlersin: {1//2} ile {1//3}, {3//6} ile {2//6} olur. Kök derecesi de aslında bir paydadır; çünkü √2 = 2^{{1//2}} ve √[3]3 = 3^{{1//3}}. Paydaları 6\'da eşitlersen 2^{{3//6}} ve 3^{{2//6}} olur: ikisi de 6. dereceden köktür ve artık tek kök altında çarpılabilir.',
      soru: { s: '√2·√[3]2 hangisine eşittir?', o: ['√[6]4', '√[6]32', '√[5]4'], d: 1, y: ['derece', null, 'derece'], neden: '√2 = √[6](2^3) ve √[3]2 = √[6](2^2). Çarpım: √[6](2^5) = √[6]32.' },
    },
    {
      id: 'eslenik', baslik: 'Paydayı kökten kurtarmak: eşlenik',
      giris: '{1//√2} + {1//2√3} toplamını yapmak için paydaları eşitlemek gerekir; ama paydalarda kök varken bu zordur. Önce paydalar kökten kurtarılır.',
      metin: [
        'Paydada tek bir karekök varsa kesri o kökle genişletirsin: √a·√a = a olduğundan kök kalkar. {1//√3} = {√3//3}. Pay da aynı sayıyla çarpılır; yoksa kesrin değeri değişir.',
        'Paydada √a − √b gibi iki terim varsa onu kendisiyle çarpmak işe yaramaz. İşareti değiştirilmiş hâliyle, yani **eşleniğiyle** çarparsın: (√a − √b)·(√a + √b) = a − b. Ortadaki terimler birbirini götürür ve kök kalmaz.',
        'Tabloda bunu adım adım gör: (√5 − √2)·(√5 + √2) = 5 + √10 − √10 − 2 = 3.',
      ],
      tablo: {
        ad: 'Eşlenikle çarp',
        bas: ['İşlem', 'Adımlar', 'Sonuç'],
        sat: [
          ['√3·√3', '√9', '3'],
          ['{1//√3}·{√3//√3}', '{√3//√3·√3}', '{√3//3}'],
          ['(√5 − √2)·(√5 + √2)', '5 + √10 − √10 − 2', '3'],
          ['(2√2 + 1)·(2√2 − 1)', '8 − 2√2 + 2√2 − 1', '7'],
          ['{1//√5 − √2}·{√5 + √2//√5 + √2}', '{√5 + √2//5 − 2}', '{√5 + √2//3}'],
        ],
      },
      kural: ['{1//√a} = {√a//a}', '(√a − √b)·(√a + √b) = a − b'],
      ornek: { s: '{√3//√3 − 1} − {1//√3 + 1} işleminin sonucu kaçtır?', a: ['İlk kesri √3 + 1 ile genişlet: {√3·(√3 + 1)//(√3 − 1)·(√3 + 1)} = {3 + √3//2}', 'İkinci kesri √3 − 1 ile genişlet: {√3 − 1//(√3 + 1)·(√3 − 1)} = {√3 − 1//2}', 'Paydalar eşit, payları çıkar: {3 + √3 − √3 + 1//2}', '{4//2} = 2'] },
      baska: 'Bir kökü yok etmenin yolu onu kendisiyle çarpmaktır: √5·√5 = 5. Ama paydada √5 − √2 varsa ve onu kendisiyle çarparsan ortada 2√10 gibi yeni bir kök doğar. Eşleniğiyle çarptığında ise ortadaki iki terimin biri artı biri eksi çıkar ve birbirini siler; geriye yalnızca kareler kalır: 5 − 2.',
      soru: { s: '{6//√3} kesrinin paydası rasyonel yapıldığında hangisi elde edilir?', o: ['2√3', '2', '6√3'], d: 0, y: [null, 'paydaKok', 'paydaKok'], neden: '{6//√3}·{√3//√3} = {6√3//3} = 2√3. Pay da payda da √3 ile çarpılır.' },
    },
    {
      id: 'yaklasik', baslik: 'Yaklaşık değer ve hata payı',
      gorsel: { tip: 'kare-ara', n: 3 },
      giris: 'Ahmet Bey, 1200 m² büyüklüğündeki kare arazisinin çevresini çitle çevirecek. Çit 5 metrelik paneller hâlinde satılıyor ve bir panel 1700 TL. Arazinin kenarı 20√3 metre; ama mağazaya "20√3 metre çit" diye gidilmez.',
      metin: [
        '√3 bir irrasyonel sayıdır: ondalık yazımı hiç bitmez ve tekrar etmez. Gerçek yaşamda bu yüzden yaklaşık değeri kullanılır. Yaklaşık değeri bulmanın yolu, sayıyı karesi bilinen iki sayının arasına sıkıştırmaktır.',
        '1^2 = 1 ve 2^2 = 4 olduğundan √3, 1 ile 2 arasındadır. Aralığın ortasını dene: 1,5^2 = 2,25 eder. Bu 3\'ten küçük, demek ki √3, 1,5 ile 2 arasında. Yine ortayı dene: 1,75^2 = 3,0625 eder. Bu 3\'e çok yakın; √3 ≈ 1,75 alınabilir.',
        'Yaklaşık değer kullanıldığında sonuç da yaklaşıktır; aradaki farka **hata payı** denir. √3\'ün değeri 1,732… olduğundan 1,75 almak sonucu biraz büyütür. Çit alırken bu iyidir: eksik kalmasındansa biraz artması istenir.',
      ],
      tablo: {
        ad: 'Araya sıkıştır',
        bas: ['Deneme', 'Karesi', '3 ile karşılaştır', 'Sonuç'],
        sat: [['1', '1', 'küçük', '√3 > 1'], ['2', '4', 'büyük', '√3 < 2'], ['1,5', '2,25', 'küçük', '√3 > 1,5'], ['1,75', '3,0625', 'biraz büyük', '√3 ≈ 1,75']],
      },
      kural: ['a^2 < x < b^2 ise a < √x < b   (a ≥ 0, b ≥ 0)', 'Yaklaşık değerle bulunan sonuç da yaklaşıktır.'],
      ornek: { s: 'Ahmet Bey bu işi en az kaç TL harcayarak tamamlar? √3 yerine 1,75 al.', a: ['Bir kenar: 20√3 ≈ 20·1,75 = 35 m', 'Çevre: 4·35 = 140 m', 'Panel sayısı: 140 ÷ 5 = 28', 'Tutar: 28·1700 = 47 600 TL'] },
      baska: 'Bir sayı tahmin oyunu oyna: "Karesi 3 eden sayıyı tuttum." 1 dersin, "daha büyük" denir. 2 dersin, "daha küçük". 1,5 dersin, "daha büyük". 1,75 dersin, "çok yaklaştın, azıcık küçüğü". Her tahminde aralık yarıya iner. İstediğin kadar yaklaşabilirsin ama tam üstüne hiç basamazsın; irrasyonel sayı budur.',
      soru: { s: '√40 hangi iki tam sayının arasındadır?', o: ['5 ile 6', '6 ile 7', '19 ile 21'], d: 1, y: [null, null, 'yari'], neden: '6^2 = 36 ve 7^2 = 49. 36 < 40 < 49 olduğundan √40, 6 ile 7 arasındadır.' },
    },
  ],
  ozet: [
    'Kök, kuvvetin tersidir: √[n]a, n. kuvveti a eden sayıdır. Karekök negatif çıkmaz: √(a^2) = |a|.',
    'Rasyonel üs köktür: x^{{m//n}} = √[n](x^m). Payda kökün derecesi, pay içerideki üs.',
    'Tam kare çarpan kök dışına karekökü olarak çıkar: √(a^2·b) = a√b.',
    'Toplama ve çıkarma yalnızca derecesi ve içi aynı olan köklerde yapılır; katsayılar toplanır, kök içleri toplanmaz.',
    'Aynı dereceli kökler tek kök altında çarpılır ve bölünür. Kökün kökünde dereceler çarpılır.',
    'Dereceler farklıysa önce eşitlenir: √[n](x^m) = √[n·k](x^{m·k}).',
    'Paydadaki kök eşlenikle çarpılarak kaldırılır: (√a − √b)·(√a + √b) = a − b.',
    'İrrasyonel bir kökün yaklaşık değeri, karesi bilinen iki sayının arasına sıkıştırılarak bulunur; sonuç da yaklaşıktır.',
  ],
  sorular: [
    {
      id: 's1', z: 1, kart: 'kok', tur: 'islem',
      s: '√81 − √[3](−8) + √((−3)^2) işleminin sonucu kaçtır?',
      o: ['10', '4', '14', '20', '8'], d: 2, y: ['kokNeg', 'kokNeg', null, null, 'kokNeg'],
      c: ['√81 = 9, çünkü 9^2 = 81', '√[3](−8) = −2, çünkü (−2)^3 = −8. Tek dereceli kökte işaret korunur', '√((−3)^2) = √9 = 3. Karekök negatif çıkmaz', '9 − (−2) + 3 = 14'],
      h: 'Math.sqrt(81) - Math.cbrt(-8) + Math.sqrt((-3)**2) === 14',
      kay: `${KITAP}, 6. Örnek tipinde`,
    },
    {
      id: 's2', z: 1, kart: 'rasyonel', tur: 'islem',
      s: '27^{{2//3}} + 16^{{3//4}} işleminin sonucu kaçtır?',
      o: ['12', '30', '11', '5', '17'], d: 4, y: ['rasyonel', 'yari', 'rasyonel', 'rasyonel', null],
      c: ['27^{{2//3}} = √[3](27^2). Önce kökü almak kolaydır: √[3]27 = 3, sonra karesi 3^2 = 9', '16^{{3//4}} = √[4](16^3). √[4]16 = 2, sonra küpü 2^3 = 8', '9 + 8 = 17'],
      h: 'Math.abs(27**(2/3) + 16**(3/4) - 17) < 1e-9',
      kay: `${KITAP}, 6. Uygulama tabloları ve Alıştırmalar 4. soru tipinde`,
    },
    {
      id: 's3', z: 1, kart: 'topla', tur: 'baglam',
      b: ['Bir deneyde iki cisim farklı yüksekliklerden bırakılmıştır. Birinci cismin yere düşme süresi √48 saniye, ikinci cismin yere düşme süresi √108 saniye olarak hesaplanmıştır.'],
      s: 'Buna göre iki cismin düşme süreleri arasındaki fark kaç saniyedir?',
      o: ['√60', '10√3', '2√3', '20√3', '2√15'], d: 2, y: ['kokTopla', null, null, 'disari', 'kokTopla'],
      c: ['Kök dışına çıkar: √108 = √(36·3) = 6√3', '√48 = √(16·3) = 4√3', 'Fark: 6√3 − 4√3 = (6 − 4)√3 = 2√3 saniye'],
      h: 'Math.abs(Math.sqrt(108) - Math.sqrt(48) - 2*Math.sqrt(3)) < 1e-9',
      kay: `${KITAP}, köklü gösterimlerle işlemler bölümünün giriş durumu (düşme süreleri)`,
    },
    {
      id: 's4', z: 2, kart: 'disari', tur: 'islem',
      s: '√45 − 2√20 + 3√80 işleminin sonucu kaçtır?',
      o: ['11√5', '5√5', '19√5', '49√5', '7√5'], d: 0, y: [null, null, null, 'disari', 'kokTopla'],
      c: ['√45 = √(9·5) = 3√5', '√20 = √(4·5) = 2√5 ve √80 = √(16·5) = 4√5', 'Yerine yaz: 3√5 − 2·2√5 + 3·4√5 = 3√5 − 4√5 + 12√5', '(3 − 4 + 12)√5 = 11√5'],
      h: 'Math.abs(Math.sqrt(45) - 2*Math.sqrt(20) + 3*Math.sqrt(80) - 11*Math.sqrt(5)) < 1e-9',
      kay: `${KITAP}, 4. Sıra Sizde ve Alıştırmalar 5. soru tipinde`,
    },
    {
      id: 's5', z: 2, kart: 'carp', tur: 'baglam',
      b: ['Kare şeklindeki iki bahçenin alanları 12 m² ve 27 m²\'dir. Bu iki bahçenin birer kenarı uç uca eklenerek kare şeklinde yeni bir bahçenin bir kenarı elde edilecektir.'],
      s: 'Buna göre yeni bahçenin alanı kaç metrekaredir?',
      o: ['75', '15', '25√3', '5√3', '39'], d: 0, y: [null, 'kare', 'kare', null, 'kokTopla'],
      c: ['Kenarlar: √12 = 2√3 m ve √27 = 3√3 m', 'Yeni kenar: 2√3 + 3√3 = 5√3 m', 'Alan: (5√3)^2 = 25·3 = 75 m²', 'Dikkat: alanları toplarsan 39 çıkar ama uç uca eklenen kenarlardır, alanlar değil'],
      h: 'Math.abs((Math.sqrt(12) + Math.sqrt(27))**2 - 75) < 1e-9',
      kay: `${KITAP}, 7. Uygulama 5. maddedeki ev planı probleminden uyarlandı`,
    },
    {
      id: 's6', z: 2, kart: 'derece', tur: 'islem',
      s: 'a = √2, b = √[3]3 ve c = √[6]6 sayılarının küçükten büyüğe sıralanışı hangisidir?',
      o: ['a < b < c', 'c < a < b', 'a < c < b', 'c < b < a', 'b < a < c'], d: 1, y: ['siralama', null, null, 'siralama', null],
      c: ['Dereceler 2, 3 ve 6; ortak derece 6', 'a = √2 = √[6](2^3) = √[6]8', 'b = √[3]3 = √[6](3^2) = √[6]9', 'c = √[6]6 olduğu gibi kalır', 'Kök içleri: 6 < 8 < 9, yani c < a < b'],
      h: '6**(1/6) < Math.SQRT2 && Math.SQRT2 < Math.cbrt(3)',
      kay: `${KITAP}, 11. Örnek ve 7. Sıra Sizde tipinde`,
    },
    {
      id: 's7', z: 2, kart: 'eslenik', tur: 'islem',
      s: '{4//√7 − √3} kesrinin paydası rasyonel yapıldığında hangisi elde edilir?',
      o: ['√7 − √3', '4·(√7 + √3)', '{2·(√7 + √3)//5}', '1', '√7 + √3'], d: 4, y: ['eslenik', 'paydaKok', 'eslenik', 'paydaKok', null],
      c: ['Paydanın eşleniği √7 + √3; kesri bununla genişlet', 'Payda: (√7 − √3)·(√7 + √3) = 7 − 3 = 4', 'Pay: 4·(√7 + √3)', '{4·(√7 + √3)//4} = √7 + √3'],
      h: 'Math.abs(4/(Math.sqrt(7)-Math.sqrt(3)) - (Math.sqrt(7)+Math.sqrt(3))) < 1e-9',
      kay: `${KITAP}, 9. Uygulama tablosu ve 13. Örnek tipinde`,
    },
    {
      id: 's8', z: 3, kart: 'yaklasik', tur: 'baglam',
      b: ['Bir okul, alanı 800 m² olan kare şeklindeki bahçesinin çevresine tel örgü çektirecektir. Tel örgü 10 metrelik toplar hâlinde satılmaktadır ve bir topun fiyatı 1500 TL\'dir. Okul yönetimi hesap yaparken √2 yerine 1,4 almıştır.'],
      s: 'Buna göre okul bu iş için en az kaç TL ödemelidir?',
      o: ['4 500', '16 500', '16 800', '18 000', '240 000'], d: 3, y: [null, 'yuvarla', 'yuvarla', null, 'yari'],
      c: ['Bir kenar: √800 = √(400·2) = 20√2 m', 'Yaklaşık değer: 20·1,4 = 28 m', 'Çevre: 4·28 = 112 m', 'Top sayısı: 112 ÷ 10 = 11,2. Yarım top satılmadığı için 12 top gerekir', 'Tutar: 12·1500 = 18 000 TL'],
      h: 'Math.ceil(Math.round(4 * 20 * 1.4) / 10) * 1500 === 18000',
      kay: `${KITAP}, 14. Örnekten uyarlandı (çit yerine tel örgü, sayılar değiştirildi)`,
    },
    {
      id: 's9', z: 2, kart: 'carp', tur: 'muhakeme',
      b: ['Zeynep, (√48 + √27)·√3 işlemini aşağıdaki adımlarla yapmıştır.'],
      t: { bas: ['Adım', 'Yapılan işlem'], sat: [['1', '√48 = 4√3'], ['2', '√27 = 3√3'], ['3', '4√3 + 3√3 = 7√3'], ['4', '7√3·√3 = 7√6'], ['5', 'Sonuç: 7√6']] },
      s: 'Buna göre Zeynep ilk hatayı hangi adımda yapmıştır?',
      o: ['1. adım', '2. adım', '3. adım', '4. adım', '5. adım'], d: 3, y: ['disari', 'disari', 'kokTopla', null, null],
      c: ['1. ve 2. adım doğru: 48 = 16·3 ve 27 = 9·3', '3. adım doğru: kök içleri aynı, katsayılar toplanır', '4. adım hatalı: √3·√3 = √9 = 3 eder. Çarpmada kök içleri çarpılır, toplanmaz', 'Doğru sonuç: 7·3 = 21'],
      h: 'Math.abs((Math.sqrt(48) + Math.sqrt(27)) * Math.sqrt(3) - 21) < 1e-9',
      kay: `${KITAP}, 1. Tema Ölçme ve Değerlendirme 11. soru tipinde: "ilk hata hangi adımda"`,
    },
    {
      id: 's10', z: 3, kart: 'topla', tur: 'muhakeme',
      s: 'a ve b pozitif gerçek sayılardır. Aşağıdaki önermelerden hangisi her zaman doğrudur?',
      o: ['√a + √b = √(a + b)', '√a·√b = √(a·b)', '√(a^2 + b^2) = a + b', '√(a·b) = a·√b', '√(√a) = √[3]a'], d: 1, y: ['kokTopla', null, 'kokTopla', 'disari', 'kokKok'],
      c: ['Küçük sayılarla dene: a = 9 ve b = 16', '√9 + √16 = 7 ama √25 = 5. Tutmadı', '√(81 + 256) = √337 ama 9 + 16 = 25 ve 25^2 = 625. Tutmadı', '√(9·16) = 12 ama 9·√16 = 36. Tutmadı. a = 16 için √(√16) = 2 ama √[3]16, 2 değildir; çünkü 2^3 = 8', '√a·√b = √(a·b) her zaman doğrudur: a^{{1//2}}·b^{{1//2}} = (a·b)^{{1//2}}; üsleri aynı olanların tabanları çarpılır'],
      h: 'Math.abs(Math.sqrt(9)*Math.sqrt(16) - Math.sqrt(9*16)) < 1e-9 && Math.sqrt(9)+Math.sqrt(16) !== Math.sqrt(25) && Math.sqrt(81+256) !== 25 && Math.sqrt(9*16) !== 9*Math.sqrt(16)',
      kay: 'Öğretim programı MAT.9.1.1 süreç bileşenleri: önerme sunma ve doğrulama',
    },
  ],
  acik: [
    {
      id: 'a1', baslik: 'Düşme süresi',
      b: ['Belli bir yükseklikten bırakılan cismin yere düşme süresi t = √({2h//g}) eşitliğiyle bulunur. Burada h yükseklik (metre), g yer çekimi ivmesidir. Bu soruda g = 10 m/sn² alınız.'],
      alt: ['5 metre yükseklikten bırakılan cismin düşme süresini bulunuz.', '20 metre yükseklikten bırakılan cismin düşme süresini bulunuz.', 'Yükseklik 4 katına çıktığında düşme süresi kaç katına çıkmıştır? Nedenini köklü gösterimin bir özelliğiyle açıklayınız.'],
      adim: [
        { p: 2, m: 'h = 5 için t = √({2·5//10}) = √1' },
        { p: 1, m: 't = 1 saniye' },
        { p: 2, m: 'h = 20 için t = √({2·20//10}) = √4' },
        { p: 1, m: 't = 2 saniye' },
        { p: 2, m: 'Süre 2 katına çıkmıştır' },
        { p: 2, m: 'Açıklama: √(4·x) = √4·√x = 2√x; kök içindeki 4 dışarı 2 olarak çıkar' },
      ],
      kay: `${KITAP}, 9. Uygulama 5. maddedeki düşme süresi probleminden uyarlandı (g = 10 alındı)`,
    },
    {
      id: 'a2', baslik: 'Paydayı rasyonel yap',
      alt: ['{1//√5 + √3} + {1//√3 − 1} işleminin sonucunu, paydaları rasyonel yaparak bulunuz.', 'Kullandığınız eşlenik ifadeleri yazınız ve neden işe yaradıklarını açıklayınız.'],
      adim: [
        { p: 2, m: 'İlk kesri √5 − √3 ile genişletme: {√5 − √3//5 − 3} = {√5 − √3//2}' },
        { p: 2, m: 'İkinci kesri √3 + 1 ile genişletme: {√3 + 1//3 − 1} = {√3 + 1//2}' },
        { p: 2, m: 'Paydalar eşit, payları toplama: {√5 − √3 + √3 + 1//2}' },
        { p: 2, m: 'Sonuç: {√5 + 1//2}' },
        { p: 2, m: 'Açıklama: (√a − √b)·(√a + √b) = a − b olduğundan eşlenikle çarpınca paydada kök kalmaz' },
      ],
      kay: `${KITAP}, 8. Sıra Sizde sorusundan uyarlandı`,
    },
    {
      id: 'a3', baslik: 'Bahçenin çiti',
      b: ['Alanı 50 m² olan kare şeklindeki bir bahçenin çevresi çitle çevrilecektir.'],
      alt: ['Bahçenin bir kenarının uzunluğunu a√b biçiminde yazınız.', '1,4 ve 1,5 sayılarının karelerini hesaplayarak √2 sayısının 1,4 ile 1,5 arasında olduğunu gösteriniz.', '√2 yerine 1,4 alarak bahçenin çevresini yaklaşık olarak bulunuz. √2 yerine 1,5 alınsaydı sonuç kaç metre değişirdi?'],
      adim: [
        { p: 2, m: '√50 = √(25·2) = 5√2 m' },
        { p: 2, m: '1,4^2 = 1,96 ve 1,5^2 = 2,25' },
        { p: 1, m: '1,96 < 2 < 2,25 olduğundan 1,4 < √2 < 1,5' },
        { p: 2, m: 'Çevre: 4·5√2 = 20√2 ≈ 20·1,4 = 28 m' },
        { p: 2, m: '1,5 alınırsa çevre 20·1,5 = 30 m bulunur' },
        { p: 1, m: 'Sonuç 2 metre değişir: yaklaşık değerin seçimi sonucu etkiler, buna hata payı denir' },
      ],
      kay: `${KITAP}, 14. Örnek; öğretim programındaki "yaklaşık değer ve hata payı" açıklaması`,
    },
  ],
};
export default k;
